changelog:
  categories:
    - title: Breaking Changes
      labels:
        - kind/breaking
    - title: Implemented enhancements
      labels:
        - kind/feature
    - title: Fixed bugs
      labels:
        - kind/bug
    - title: Other
      labels:
        - "*"
