name: Label PR based on body keyword

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Label PR
        uses: actions/github-script@v4
        with:
          async: yes
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prBody = context.payload.pull_request.body.toLowerCase().trim();

            if (prBody.startsWith('/kind')) {
              const keyword = prBody.split(' ')[1];
              const label = `kind/${keyword}`;
              console.log(`Matched label '${label}' with keyword ${keyword}`);
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [label]
              });
            }
