name: Label PR based on body keyword

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Label PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const keywords = [
              { keyword: "breaking", label: "kind/breaking" },
              { keyword: "bug", label: "kind/bug" },
              { keyword: "cleanup", label: "kind/cleanup" },
              { keyword: "documentation", label: "kind/documentation" },
              { keyword: "feature", label: "kind/feature" },
              { keyword: "hotfix", label: "kind/hotfix" }
            ];
            const prBody = context.payload.pull_request.body.toLowerCase();
            let matchedLabel = null;
            for (const keywordData of keywords) {
              if (prBody.includes(keywordData.keyword.toLowerCase())) {
                matchedLabel = keywordData.label;
                break;
              }
            }
            if (matchedLabel) {
              const labelsToAdd = [matchedLabel];
              const labelsToRemove = keywords
                .filter(keywordData => keywordData.label !== matchedLabel)
                .map(keywordData => keywordData.label);
              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labelsToAdd
              });
              await github.issues.removeLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labelsToRemove
              });
            } else {
              console.log("No matching keyword found in the PR body.");
            }
