name: Label PR based on body keyword

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Label PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const keywords = [
              { keyword: "breaking", label: "kind/breaking" },
              { keyword: "bug", label: "kind/bug" },
              { keyword: "cleanup", label: "kind/cleanup" },
              { keyword: "documentation", label: "kind/documentation" },
              { keyword: "feature", label: "kind/feature" },
              { keyword: "hotfix", label: "kind/hotfix" }
            ];
            const prBody = context.payload.pull_request.body.toLowerCase();
            for (const keywordData of keywords) {
              if (prBody.includes(keywordData.keyword.toLowerCase())) {
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  labels: [keywordData.label]
                });
                break;
              }
            }
