name: Label PRs

on:
  pull_request:
    types: [opened, edited]

jobs:
  label-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Label PRs
        uses: peter-evans/auto-label@v3
        with:
          repo-token: "${{ secrets.AGONES_BOT }}"
          configuration-path: ".github/auto-label.yml"
