name: Label PRs based on kind
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  label-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get PR body
        run: |
          body=$(cat $GITHUB_EVENT_PATH)

      - name: Check for kind
        run: |
          # Get the body of the PR
          body=$(github api get /repos/$GITHUB_REPOSITORY/issues/${{ github.event.pull_request.number }} | jq -r .body)

          # Check if the body contains the `/kind` keyword
          if [[ $body =~ '/kind (breaking|feature|bug|cleanup|documentation|hotfix)/' ]]; then
            # Get the kind of the PR
            kind=${BASH_REMATCH[1]}

            # Label the PR
            github api post /repos/$GITHUB_REPOSITORY/issues/$GITHUB_PR_ID/labels \
              -f name=$kind
          else
            # No kind found
            echo "No kind found"
          fi
