name: Label Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  label-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Label Pull Requests
        run: |
          # Get the pull request content
          content=$(gh pr view --json "$PR_NUMBER" | jq -r '.body')

          # Check if the content contains the `/kind` keyword
          if [[ $content =~ /kind/ ]]; then
            # Get the kind of pull request
            kind=${content##*/kind=}

            # Apply the appropriate label
            case "$kind" in
              feature)
                gh pr label add "$PR_NUMBER" kind/feature
                ;;
              bug)
                gh pr label add "$PR_NUMBER" kind/bug
                ;;
              breaking)
                gh pr label add "$PR_NUMBER" kind/breaking
                ;;
              cleanup)
                gh pr label add "$PR_NUMBER" kind/cleanup
                ;;                
              documentation)
                gh pr label add "$PR_NUMBER" kind/documentation
                ;;
              hotfix)
                gh pr label add "$PR_NUMBER" kind/hotfix
                ;;
              *)
                echo "Unknown kind of pull request"
                ;;
            esac
          fi
        env:
          GH_TOKEN: ${{ github.token }}
