name: Label Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Use auto-label action with additional labels based on /kind label
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.AGONES_BOT }}
      
      # Extract /kind label and map to associated label
      - name: Apply kind label to PR
        uses: actions/github-script@v5
        with:
          script: |
            const { context, github } = require('@actions/github');

            // Get the label to apply based on the value of the /kind label
            const prLabels = context.payload.pull_request.labels.map(label => label.name);
            let kindLabel;
            if (prLabels.includes('/kind breaking')) {
              kindLabel = 'kind/breaking';
            } else if (prLabels.includes('/kind bug')) {
              kindLabel = 'kind/bug';
            } else if (prLabels.includes('/kind cleanup')) {
              kindLabel = 'kind/cleanup';
            } else if (prLabels.includes('/kind documentation')) {
              kindLabel = 'kind/documentation';
            } else if (prLabels.includes('/kind feature')) {
              kindLabel = 'kind/feature';
            } else if (prLabels.includes('/kind hotfix')) {
              kindLabel = 'kind/hotfix';
            }

            // If a matching kind label was found, apply it to the PR
            if (kindLabel) {
              github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [kindLabel]
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
