name: Label PR based on body keyword
on:
  pull_request:
    types: [opened, reopened]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Label PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const keywords = {
              "breaking": "kind/breaking",
              "bug": "kind/bug",
              "feature": "kind/feature",
              "cleanup": "kind/cleanup",
              "documentation": "kind/documentation",
              "hotfix": "kind/hotfix"
            };
            const prBody = context.payload.pull_request.body.toLowerCase();
            (async () => {
              for (const [keyword, label] of Object.entries(keywords)) {
                if (prBody.includes(keyword)) {
                  console.log(`Adding label '${label}' based on keyword '${keyword}'`);
                  await github.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.payload.pull_request.number,
                    labels: [label]
                  });
                  break; // Exit loop once a keyword is found
                }
              }
            })();
