name: Label PR based on body keyword

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Label PR
        uses: actions/github-script@v4
        with:
          async: yes
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const keywords = {
              "breaking": "kind/breaking",
              "bug": "kind/bug",
              "feature": "kind/feature",
              "cleanup": "kind/cleanup",
              "documentation": "kind/documentation",
              "hotfix": "kind/hotfix"
            };

            const prBody = context.payload.pull_request.body.toLowerCase().trim();
            const prLabels = [];

            const regex = /^\/kind\s(.+)$/m;
            const match = prBody.match(regex);

            console.log(`PR body: '${prBody}'`);
            console.log(`Regex match: '${match}'`);

            if (match && match[1] in keywords) {
              const keyword = match[1];
              const label = keywords[keyword];
              console.log(`Adding label: '${label}' based on keyword '${keyword}'`);
              prLabels.push(label);
            } else {
              console.log(`Adding label: 'kind/other' as no matching keyword found.`);
              prLabels.push("kind/other");
            }

            try {
              // Retrieve the PR's commits using the GitHub REST API
              const commitsResponse = await github.pulls.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });
              const commits = commitsResponse.data;

              // Calculate the total commit size
              const totalCommitSize = commits.length;

              console.log(`Total commit size: ${totalCommitSize}`);

              // Label the PR based on commit size
              let sizeLabel;
              if (totalCommitSize < 9) {
                sizeLabel = 'size:XS';
              } else if (totalCommitSize < 49) {
                sizeLabel = 'size:S';
              } else if (totalCommitSize < 249) {
                sizeLabel = 'size:M';
              } else if (totalCommitSize < 999) {
                sizeLabel = 'size:L';
              } else {
                sizeLabel = 'size:XL';
              }

              await github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: [...prLabels, sizeLabel]
              });
            } catch (error) {
              console.error(`Error retrieving commits: ${error}`);
              // Handle the error or perform any necessary actions
            }
