name: Label PRs based on kind
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  label-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get PR body
        run: |
          body=$(curl -s -H "Authorization: Bearer ${{ secrets.AGONES_BOT }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | jq -r '.body')
          if [[ -z $body ]]; then
            echo "Failed to retrieve PR body"
            exit 1
          else
            echo "PR body: $body"
          fi
      - name: Check for kind
        run: |
          # Remove leading and trailing whitespace from the body
          body=$(echo "$body" | awk '{$1=$1};1')

          # Check if the body contains the `/kind` keyword
          if [[ $body =~ '/kind ' ]]; then
            # Extract the kind from the body
            kind=$(grep -oP '/kind \K\w+' <<< "$body")
            echo "kind: $kind"
        
            # Label the PR
            curl -X POST -H "Authorization: Bearer ${{ secrets.AGONES_BOT }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels" \
              -d "{\"labels\":[\"$kind\"]}"
          else
            # No kind found
            echo "No kind found"
            echo "PR body: $body"
          fi

