name: Label PRs

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on body
        uses: actions/github-script@0.6.0
        env:
          KEYWORD_1: "bug"
          KEYWORD_2: "feature"
        with:
          github-token: ${{ secrets.AGONES_BOT }}
          script: |
            const keywords = [process.env.KEYWORD_1, process.env.KEYWORD_2];
            const prBody = context.payload.pull_request.body.toLowerCase();
            const labelsToAdd = keywords.filter(keyword => prBody.includes(keyword)).map(keyword => `label:${keyword}`);
            if (labelsToAdd.length > 0) {
              github.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels: labelsToAdd
              });
            }
