name: Label Pull Requests

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  label-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Label Pull Requests
        run: |
          # Get the pull request content
          content=$(gh pr show --json "$PR_NUMBER" | jq -r '.body')
  
          # Check if the content contains the `/kind` keyword
          if [[ $content =~ /kind/ ]]; then
            # Get the kind of pull request
            kind=${content##*/kind=}
  
            # Apply the appropriate label
            case "$kind" in
              feature)
                gh pr label add "$PR_NUMBER" feature
                ;;
              bug)
                gh pr label add "$PR_NUMBER" bug
                ;;
              breaking)
                gh pr label add "$PR_NUMBER" breaking
                ;;
              *)
                echo "Unknown kind of pull request"
                ;;
            esac
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
