name: Label PR based on body keyword

on:
  pull_request:
    types: [opened, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Label PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const keywords = [
              "breaking",
              "bug",
              "cleanup",
              "documentation",
              "feature",
              "hotfix"
            ];
            const prBody = context.payload.pull_request.body.toLowerCase();
            for (const keyword of keywords) {
              if (prBody.includes(keyword)) {
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.pull_request.number,
                  labels: [keyword]
                });
              }
            }
